### ISSUE TITLE
Target, during game stuff

### ISSUE THREAD

**Issue by victorgaitour** [kingalex11235/Assassin#22]
When you create a game and then have someone join your game the home page crashes. Additionally, on the target page there needs to be a camera. I have added what needs to be added from my code into app.py, it checks if the uploaded photo is of a face, and then if that face is of a registered user. If it is, it returns the username it thinks that the uploaded photo is of, if it isn't it returns false. Fb message if you need me.

**Comment by kingalex11235** [comment]
Home page crash is fixed and camera upload works on mobile with the picture select button.
